CC = riscv64-elf-gcc  # 选择自己的编译器路径，这里使用通过brew安装的RISC-V架构的交叉编译器
CFLAGS = -g -Wall -std=c99 -march=rv32im -mabi=ilp32 -c  # 编译器参数
OBJDUMP = riscv64-elf-objdump  

build:
	$(CC) $(CFLAGS) PrintFunc.c -o print.o  
objdump:
	$(OBJDUMP) -d print.o  
clean:
	rm -f print.o  